"""Core data schemas for analysis workflow."""

from datetime import datetime
from enum import StrEnum
from typing import Literal
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class FindingLabel(StrEnum):
    """Constrained vocabulary for radiological findings."""

    CONSOLIDATION = "consolidation"
    EFFUSION = "effusion"
    PNEUMOTHORAX = "pneumothorax"
    CARDIOMEGALY = "cardiomegaly"
    EDEMA = "edema"
    NODULE = "nodule"
    ATELECTASIS = "atelectasis"
    NORMAL = "normal"


class DeltaStatus(StrEnum):
    """Status of change between prior and current imaging."""

    IMPROVED = "improved"
    STABLE = "stable"
    WORSENED = "worsened"
    UNCERTAIN = "uncertain"


class UncertaintyLevel(StrEnum):
    """Confidence level for findings."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class EvidenceSourceType(StrEnum):
    """Types of evidence sources for claims."""

    PRIOR_IMAGE = "prior_image"
    CURRENT_IMAGE = "current_image"
    FHIR_CONTEXT = "fhir_context"
    GUIDELINE = "guideline"
    DICTATION = "dictation"
    SIMILAR_CASE = "similar_case"  # From CXR Foundation retrieval
    ZERO_SHOT = "zero_shot"  # From MedSigLIP classification


class BoundingBox(BaseModel):
    """Anatomical localization coordinates."""

    x: int = Field(ge=0, description="X coordinate (top-left)")
    y: int = Field(ge=0, description="Y coordinate (top-left)")
    w: int = Field(gt=0, description="Width")
    h: int = Field(gt=0, description="Height")


class Finding(BaseModel):
    """A single radiological finding with delta analysis."""

    label: FindingLabel
    delta: DeltaStatus
    rationale: str = Field(min_length=1, max_length=500)
    evidence_refs: list[EvidenceSourceType] = Field(min_length=1)
    bounding_box: BoundingBox | None = None
    uncertainty: UncertaintyLevel = UncertaintyLevel.MEDIUM


class DraftReport(BaseModel):
    """Generated radiology report sections."""

    findings: str = Field(min_length=1, description="Findings section text")
    impression: str = Field(min_length=1, description="Impression section text")


class AuditEntry(BaseModel):
    """Single entry in the audit trail mapping claim to evidence."""

    claim: str = Field(min_length=1, max_length=500)
    source_type: EvidenceSourceType
    source_ref: str = Field(min_length=1, description="Reference to specific evidence")
    uncertainty: UncertaintyLevel


class WorkflowStep(StrEnum):
    """Steps in the analysis workflow."""

    INTAKE = "intake"
    PREPROCESS = "preprocess"
    RETRIEVE_CONTEXT = "retrieve_context"
    RETRIEVE_EVIDENCE = "retrieve_evidence"  # CXR Foundation + MedSigLIP
    INFERENCE = "inference"
    VALIDATE = "validate"
    ASSEMBLE = "assemble"


class StepStatus(StrEnum):
    """Status of a workflow step."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETE = "complete"
    ERROR = "error"


class WorkflowStepUpdate(BaseModel):
    """Status update for a workflow step."""

    step: WorkflowStep
    status: StepStatus
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    message: str | None = None
    duration_ms: int | None = None


# Request/Response Models


class AnalysisRequest(BaseModel):
    """Request to analyze a pair of CXR images."""

    prior_image: str = Field(description="Base64-encoded prior CXR image")
    current_image: str = Field(description="Base64-encoded current CXR image")
    patient_id: str = Field(default="anonymous", min_length=1, max_length=100)
    dictation_audio: str | None = Field(default=None, description="Base64-encoded audio")
    fhir_context: dict | None = Field(default=None, description="FHIR bundle JSON")


class AnalysisResult(BaseModel):
    """Complete analysis result."""

    job_id: UUID = Field(default_factory=uuid4)
    patient_id: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    findings: list[Finding]
    delta_summary: str = Field(min_length=1, description="Bullet-point delta summary")
    draft_report: DraftReport
    audit_trail: list[AuditEntry]
    retrieval_evidence: "RetrievalEvidenceResult | None" = Field(
        default=None, description="Evidence from CXR Foundation and MedSigLIP retrieval"
    )
    model_narrative: str | None = Field(
        default=None,
        description="Raw narrative text generated by the LLM (MedGemma GGUF)",
    )
    disclaimer: str = Field(
        default="Draft only—requires clinician verification. "
        "Not intended for use without appropriate validation and adaptation."
    )


class AnalysisStatus(BaseModel):
    """Status of an ongoing analysis job."""

    job_id: UUID
    status: Literal["pending", "processing", "complete", "error"]
    current_step: WorkflowStep | None = None
    steps: list[WorkflowStepUpdate] = Field(default_factory=list)
    progress_percent: int = Field(ge=0, le=100, default=0)
    error_message: str | None = None


class HealthResponse(BaseModel):
    """Health check response."""

    status: Literal["healthy", "unhealthy"]
    version: str
    model_loaded: bool
    device: str


# Transcription schemas


class TranscriptionRequest(BaseModel):
    """Request to transcribe audio."""

    audio: str = Field(description="Base64-encoded audio data")
    language: str = Field(default="en", description="Language code")


class TranscriptionTimestamp(BaseModel):
    """Word-level timestamp."""

    start: float
    end: float
    text: str


class TranscriptionResponse(BaseModel):
    """Transcription result."""

    text: str = Field(description="Transcribed text")
    confidence: float = Field(ge=0, le=1, description="Confidence score")
    timestamps: list[TranscriptionTimestamp] = Field(default_factory=list)
    source: str = Field(description="ASR engine used: medasr or whisper")


# Retrieval Evidence schemas (HAI-DEF integration)


class SimilarCaseResult(BaseModel):
    """A similar case from CXR Foundation retrieval."""

    case_id: str
    similarity_score: float = Field(ge=0, le=1)
    known_findings: list[str]
    delta_label: str
    source: str = Field(description="Dataset source (e.g., NIH-CXR14)")
    description: str | None = None


class ZeroShotResult(BaseModel):
    """Zero-shot classification result from MedSigLIP."""

    label: str
    confidence: float = Field(ge=0, le=1)


class GuidelineMatchResult(BaseModel):
    """Matched guideline from MedSigLIP retrieval."""

    title: str
    source: str
    text: str
    similarity_score: float = Field(ge=0, le=1)
    finding_type: str
    citation: str


class RetrievalEvidenceResult(BaseModel):
    """Combined retrieval evidence from CXR Foundation and MedSigLIP."""

    similar_cases: list[SimilarCaseResult] = Field(default_factory=list)
    zero_shot_predictions: list[ZeroShotResult] = Field(default_factory=list)
    guideline_matches: list[GuidelineMatchResult] = Field(default_factory=list)
    case_retrieval_confidence: float = Field(ge=0, le=1, default=0.0)
    overall_confidence: float = Field(ge=0, le=1, default=0.0)
    evidence_summary: str = ""
    classification_agreement: str | None = None  # "high", "medium", "low"
